name: potteriana_ult
description: "A new Flutter project."
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter
  auto_route: ^9.2.2


  cupertino_icons: ^1.0.8
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  dio: ^5.7.0
  flutter_bloc: ^8.1.6
  get_it: ^8.0.3
  graphql: ^5.2.0-beta.10
  pull_to_refresh_flutter3: ^2.0.2
  cached_network_image: ^3.4.1
  intl: ^0.20.1
  url_launcher: ^6.3.1
  wav: ^1.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  auto_route_generator: ^9.0.0
  build_runner: ^2.4.13
  flutter_lints: ^4.0.0
  freezed: ^2.5.7
  json_serializable: ^6.9.0
  graphql_codegen: ^1.1.1

flutter:

  assets:
    - assets/images/happyLittleTriangle.gif
    - assets/images/question_mark.png
    - assets/images/background_cover.jpg
  uses-material-design: true


